/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Action;
import org.xtext.example.mydsl.myDsl.CasDeTest;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Cas De Test</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CasDeTestImpl#getTitreCasDeTest <em>Titre Cas De Test</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.CasDeTestImpl#getActions <em>Actions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CasDeTestImpl extends MinimalEObjectImpl.Container implements CasDeTest
{
  /**
   * The default value of the '{@link #getTitreCasDeTest() <em>Titre Cas De Test</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitreCasDeTest()
   * @generated
   * @ordered
   */
  protected static final String TITRE_CAS_DE_TEST_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitreCasDeTest() <em>Titre Cas De Test</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitreCasDeTest()
   * @generated
   * @ordered
   */
  protected String titreCasDeTest = TITRE_CAS_DE_TEST_EDEFAULT;

  /**
   * The cached value of the '{@link #getActions() <em>Actions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getActions()
   * @generated
   * @ordered
   */
  protected EList<Action> actions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CasDeTestImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.CAS_DE_TEST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitreCasDeTest()
  {
    return titreCasDeTest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitreCasDeTest(String newTitreCasDeTest)
  {
    String oldTitreCasDeTest = titreCasDeTest;
    titreCasDeTest = newTitreCasDeTest;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.CAS_DE_TEST__TITRE_CAS_DE_TEST, oldTitreCasDeTest, titreCasDeTest));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<Action> getActions()
  {
    if (actions == null)
    {
      actions = new EObjectContainmentEList<Action>(Action.class, this, MyDslPackage.CAS_DE_TEST__ACTIONS);
    }
    return actions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.CAS_DE_TEST__ACTIONS:
        return ((InternalEList<?>)getActions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.CAS_DE_TEST__TITRE_CAS_DE_TEST:
        return getTitreCasDeTest();
      case MyDslPackage.CAS_DE_TEST__ACTIONS:
        return getActions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.CAS_DE_TEST__TITRE_CAS_DE_TEST:
        setTitreCasDeTest((String)newValue);
        return;
      case MyDslPackage.CAS_DE_TEST__ACTIONS:
        getActions().clear();
        getActions().addAll((Collection<? extends Action>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CAS_DE_TEST__TITRE_CAS_DE_TEST:
        setTitreCasDeTest(TITRE_CAS_DE_TEST_EDEFAULT);
        return;
      case MyDslPackage.CAS_DE_TEST__ACTIONS:
        getActions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.CAS_DE_TEST__TITRE_CAS_DE_TEST:
        return TITRE_CAS_DE_TEST_EDEFAULT == null ? titreCasDeTest != null : !TITRE_CAS_DE_TEST_EDEFAULT.equals(titreCasDeTest);
      case MyDslPackage.CAS_DE_TEST__ACTIONS:
        return actions != null && !actions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (titreCasDeTest: ");
    result.append(titreCasDeTest);
    result.append(')');
    return result.toString();
  }

} //CasDeTestImpl
