/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.CasDeTest;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Scenario;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ScenarioImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ScenarioImpl#getTitleScenario <em>Title Scenario</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.ScenarioImpl#getCasDeTests <em>Cas De Tests</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ScenarioImpl extends MinimalEObjectImpl.Container implements Scenario
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getTitleScenario() <em>Title Scenario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitleScenario()
   * @generated
   * @ordered
   */
  protected static final String TITLE_SCENARIO_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTitleScenario() <em>Title Scenario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTitleScenario()
   * @generated
   * @ordered
   */
  protected String titleScenario = TITLE_SCENARIO_EDEFAULT;

  /**
   * The cached value of the '{@link #getCasDeTests() <em>Cas De Tests</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCasDeTests()
   * @generated
   * @ordered
   */
  protected EList<CasDeTest> casDeTests;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ScenarioImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SCENARIO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SCENARIO__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getTitleScenario()
  {
    return titleScenario;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTitleScenario(String newTitleScenario)
  {
    String oldTitleScenario = titleScenario;
    titleScenario = newTitleScenario;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SCENARIO__TITLE_SCENARIO, oldTitleScenario, titleScenario));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CasDeTest> getCasDeTests()
  {
    if (casDeTests == null)
    {
      casDeTests = new EObjectContainmentEList<CasDeTest>(CasDeTest.class, this, MyDslPackage.SCENARIO__CAS_DE_TESTS);
    }
    return casDeTests;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.SCENARIO__CAS_DE_TESTS:
        return ((InternalEList<?>)getCasDeTests()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SCENARIO__NAME:
        return getName();
      case MyDslPackage.SCENARIO__TITLE_SCENARIO:
        return getTitleScenario();
      case MyDslPackage.SCENARIO__CAS_DE_TESTS:
        return getCasDeTests();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SCENARIO__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.SCENARIO__TITLE_SCENARIO:
        setTitleScenario((String)newValue);
        return;
      case MyDslPackage.SCENARIO__CAS_DE_TESTS:
        getCasDeTests().clear();
        getCasDeTests().addAll((Collection<? extends CasDeTest>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SCENARIO__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.SCENARIO__TITLE_SCENARIO:
        setTitleScenario(TITLE_SCENARIO_EDEFAULT);
        return;
      case MyDslPackage.SCENARIO__CAS_DE_TESTS:
        getCasDeTests().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SCENARIO__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.SCENARIO__TITLE_SCENARIO:
        return TITLE_SCENARIO_EDEFAULT == null ? titleScenario != null : !TITLE_SCENARIO_EDEFAULT.equals(titleScenario);
      case MyDslPackage.SCENARIO__CAS_DE_TESTS:
        return casDeTests != null && !casDeTests.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", titleScenario: ");
    result.append(titleScenario);
    result.append(')');
    return result.toString();
  }

} //ScenarioImpl
