/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getTitleScenario <em>Title Scenario</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getCasDeTests <em>Cas De Tests</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Scenario#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Title Scenario</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Title Scenario</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Title Scenario</em>' attribute.
   * @see #setTitleScenario(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_TitleScenario()
   * @model
   * @generated
   */
  String getTitleScenario();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Scenario#getTitleScenario <em>Title Scenario</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Title Scenario</em>' attribute.
   * @see #getTitleScenario()
   * @generated
   */
  void setTitleScenario(String value);

  /**
   * Returns the value of the '<em><b>Cas De Tests</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.CasDeTest}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Cas De Tests</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Cas De Tests</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_CasDeTests()
   * @model containment="true"
   * @generated
   */
  EList<CasDeTest> getCasDeTests();

} // Scenario
